### ISSUE TITLE
Crash on SetDeviceString

### ISSUE THREAD

**Issue by iskalinov13** [bugfender/BugfenderSDK-iOS#67] opened 2021-04-15 10:49 UTC
BugfenderSDK 1.10 
Xcode 12.4
Hi, all! I have an issue while setting device string within AppDelegate. 
Bugfender.setDeviceString() causes the run time exception. 
Thread 1: "[<__NSDictionaryI 0x600000069340> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key merchantId."

Also, unit_tests(fastlane) is not seeing the BugfenderSDK.
<img width="874" alt="Screenshot 2021-04-15 at 16 48 53" src="https://user-images.githubusercontent.com/38553874/114857769-7a152600-9e0a-11eb-8166-845ad09fc6a2.png">

**Comment by hungdaUBI** [comment] 2021-04-16 03:57
BugfenderSDK 1.10.1
Xcode 12.4

My client also causes crash with the same issue when using Bugfender.setDeviceString(user.account, forKey: "userAccount")
Deleting and reinstalling the app causes the same crash. 
```
Fatal Exception: NSUnknownKeyException
[<__NSDictionaryI 0x2807519e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key userAccount.
```
![Screen Shot 2021-04-16 at 11 28 08 AM](https://user-images.githubusercontent.com/64835701/114968068-2b1dce00-9ea8-11eb-95f1-be3471772633.png)

**Comment by jgimenez** [comment] 2021-04-16 07:11
Hi there, we're working on an update to fix this, but unfortunately, we can't reproduce the crash. Are you able to reproduce it reliably?

**Comment by hungdaUBI** [comment] 2021-04-16 10:41
It happened randomly. I can't reproduce it.

**Comment by jgimenez** [comment] 2021-04-16 11:01
We just published a potential fix here, it would be great if someone can confirm this one works, since we can't still reproduce the problem.

https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.10.2

**Comment by iskalinov13** [comment] 2021-04-19 09:00
HI! Wow, I am happy. But how to test it? can you leave the path for pod? Example: pod 'BugFender' ~> '1.10.2' :git => ????

**Comment by jgimenez** [comment] 2021-04-19 09:03
It's not released in cocoapods yet, this is a beta only for now. You can install the binary manually if you want to test it

**Comment by iskalinov13** [comment] 2021-04-19 09:21
![photo_2021-04-19 15 19 17](https://user-images.githubusercontent.com/38553874/115212792-b4d8d000-a122-11eb-8062-5a1a03b122a2.jpeg)
Also I don't find anything related to this issue. I can't upload my app to testflight with bugfender, unit test always fails.

**Comment by jgimenez** [comment] 2021-04-19 14:48
Released version:
https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.10.2

**Closed by jgimenez** 2021-04-19 14:48 UTC

**Comment by Tixamaster** [comment] 2021-05-23 12:03
Hi,

I use the newest version (1.10.2) over SPM and also get this error. It worked fine for weeks but since last week (no code change in this area) I get the same error as mentioned above. I could only solve it by removing it from the code.
Could you maybe double check where this issue comes from? Because it affected our users as it worked in testing and changed from one day to another.  

Here again the error log:
```

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSDictionaryI 0x280204e50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key userId.'
*** First throw call stack:
(0x1a46825b4 0x1b91017a8 0x1a45866d4 0x1a58fbfa0 0x107401888 0x10741cdec 0x10741bea0 0x107417768 0x102e4f6dc 0x102e4e868 0x102e048f4 0x102e04a38 0x103c4dbfc 0x107798064 0x107799d90 0x10779c8c8 0x1077adde0 0x1077ae79c 0x1f009e768 0x1f00a574c)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSDictionaryI 0x280204e50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key userId.'
terminating with uncaught exception of type NSException
```

Thank you!

**Comment by jgimenez** [comment] 2021-05-25 08:16
@Tixamaster I think I found the reason. The 1.10.2 git tag points to the 1.10.1 binary:
https://github.com/bugfender/BugfenderSDK-iOS/blob/f78687b15eec890ff6e6789a654481fb85f7d9aa/Package.swift

I just updated the tag. You'll likely need to pull again the file and you should be getting the right one now.
