### ISSUE TITLE
Bugfender SDK Crash in v1.10.2 with NSPropertyListSerialization

### ISSUE THREAD

**Issue by macfanatic** [bugfender/BugfenderSDK-iOS#69] opened 2021-06-25 20:36 UTC
Bugfender SDK: 1.10.2
Xcode 12.5
Bitcode enabled: yes
Cocoapods: 1.10.1

I just upgraded from 1.9.2 to 1.10.2 after upgrading to Xcode 12.5 and we have noticed a new crash, apparently in Bugfender itself (see below) in crashlytics.

![Screen Shot 2021-06-25 at 4 34 43 PM](https://user-images.githubusercontent.com/162970/123482503-43f6de00-d5d3-11eb-8966-496a7b9da4f8.png)

```
Crashed: com.apple.root.background-qos
0  CoreFoundation                 0x182e23c14 CFGetTypeID + 92
1  CoreFoundation                 0x182e1510c _CFAppendXML0 + 68
2  CoreFoundation                 0x182e15c60 _CFAppendXML0 + 2968
3  CoreFoundation                 0x182e15c60 _CFAppendXML0 + 2968
4  CoreFoundation                 0x182e1202c _CFPropertyListCreateXMLData + 188
5  CoreFoundation                 0x182e13f2c CFPropertyListCreateData + 220
6  Foundation                     0x1840fbe14 +[NSPropertyListSerialization dataWithPropertyList:format:options:error:] + 52
7  BugfenderSDK                   0x10100e44c _hidden#1830_ + 150 (__hidden#1862_:150)
8  libdispatch.dylib              0x182a9924c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x182a9adb0 _dispatch_client_callout + 20
10 libdispatch.dylib              0x182aaba68 _dispatch_root_queue_drain + 656
11 libdispatch.dylib              0x182aac120 _dispatch_worker_thread2 + 116
12 libsystem_pthread.dylib        0x1cdc957d8 _pthread_wqthread + 216
13 libsystem_pthread.dylib        0x1cdc9c76c start_wqthread + 8
```

**Comment by jgimenez** [comment] 2021-06-28 16:45
Hi there, it would be great to know what's the reason displayed for crash. This usually appears above the screenshot you took. Also, does it happen always or only on some specific devices? Thanks.

**Comment by macfanatic** [comment] 2021-06-29 12:23
We only support iPad devices, and looks like everyone is using iOS 14.

<img width="1205" alt="Screen Shot 2021-06-29 at 8 23 20 AM" src="https://user-images.githubusercontent.com/162970/123796635-544cd880-d8b3-11eb-9245-ded82ccb510f.png">

**Comment by jgimenez** [comment] 2021-06-29 12:41
Thanks for the device information. What about the reason for the crash?

**Comment by macfanatic** [comment] 2021-06-29 13:53
I don't see anything else on this page other than a sidebar on the left to switch between google products.  Is there something specifically you want to see and could share steps to get access to?

We log to Bugfender and Crashlytics simultaneously, and I can see that the crash doesn't appear related to any exact action just by reviewing the logs in Crashlytics (ie, different parts of the app, different time periods of usage in the app, etc).

I'm assuming this is crashing when Bugfender attempts to intermittently transmit information on a background thread, as that makes the most sense for the timing.

**Comment by jgimenez** [comment] 2021-07-01 11:16
Thanks @macfanatic , this information should be enough to locate the crash. We're already working on it.

**Comment by jgimenez** [comment] 2021-07-08 09:37
As discussed in private, this is likely to be a memory corruption issue, not necessarily caused by Bugfender. I'm closing this for now, please feel free to reopen if necessary.

**Closed by jgimenez** 2021-07-08 09:37 UTC
