### ISSUE TITLE
NSInvalidArgumentException: Can't use in/contains operator with collection 0 (not a collection)

### ISSUE THREAD

**Issue by softeip** [bugfender/BugfenderSDK-iOS#65] opened 2021-03-10 15:24 UTC
SDK: BFLibraryVersionNumber_1_10_0  61

Hi there
I use Xamarin.iOS binding project for bugfender static lib and my app crashes. It happens not constantly but after allowing notifications by user (first time app launch) or approximately after 1 sec from app launch (not the first time launch). I tried to symbolicate crash report and found the following lines

```
*** Terminating app due to uncaught exception 'SIGABRT', reason: 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Can't use in/contains operator with collection 0 (not a collection)
Native stack trace:
	0   CoreFoundation                      0x00000001a6f869ec __44+[UIViewController(APMScreenClassName) load]_block_invoke (in MyApp) + 628
	1   libobjc.A.dylib                     0x00000001bb30cb54 objc_exception_throw + 56
	2   Foundation                          0x00000001a819ed20 MSplcrash_async_thread_state_set_reg (in MyApp) + 648
	3   Foundation                          0x00000001a8144bd4 (anonymous namespace)::Demangler::demangleGlobal() (in MyApp) (bfsdk_Demangle.cpp:598)
	4   Foundation                          0x00000001a82499cc apmpb_alloc_property_filter_arrays (in MyApp) + 4
	5   Foundation                          0x00000001a81242f4 bfsdk_addContextualInfoToEvent (in MyApp) (BFSDK_KSCrashMonitor_System.m:610)
	6   MyApp                               0x0000000102d72040 -[BFDeviceDetailManager allKeyValuesDictionary] (in MyApp) (BFDeviceDetailManager.m:0)
	7   MyApp                               0x0000000102d3c6c0 -[BFLoggerManager bgf_updateLoggerStateWithCompletionBlock:] (in MyApp) (BFLoggerManager.m:688)
	8   MyApp                               0x0000000102d3caec -[BFLoggerManager bgf_notificationReceived:] (in MyApp) (BFLoggerManager.m:736)
	.......
```
The previous version was old but worked well without issues.
Removal of the bugfender lib from the project seems to get the crash fixed, so I've created a new issue here
This issue is related to different iOS version (13.3, 14.4) and different iPhone's (8+, XR)

**Comment by jgimenez** [comment] 2021-03-11 16:40
It looks like this is happening because NSUserDefaults.standardUserDefaults returns nil, which is unusual but seems that could happen. We're still investigating why this could be, and why we never found this situation before.

**Comment by softeip** [comment] 2021-03-11 16:46
Thank you
I will check if it returns nil on my side later

**Comment by jgimenez** [comment] 2021-03-11 16:50
OK! Here's a bit more information, in case you want to do some checks: it looks like NSUserDefaults.standardUserDefaults returns nil sometimes, depending on the state of the device, even if this is not in the docs:

 * https://stackoverflow.com/questions/20269116/nsuserdefaults-losing-its-keys-values-when-phone-is-rebooted-but-not-unlocked?answertab=oldest#tab-top
 * https://developer.apple.com/forums/thread/28030

I also see this specific crash happens on `-[BFLoggerManager bgf_notificationReceived:]` which is triggered by NSNotificationCenter when the app is going to the background or came back to the foreground.

**Comment by softeip** [comment] 2021-03-15 13:36
`which is triggered by NSNotificationCenter when the app is going to the background or came back to the foreground`
Figured out that NSUserDefaults.standardUserDefaults can return different instances after app went to bg or returned back to fg. In my code it was referencing old instance. Looks like synchronize() call was in a conflict with new instance of user defaults that was used by lib. Calling NSUserDefaults.standardUserDefaults each time I need to do some changes fixes this issue for me. I am going to give a build to a tester and then will post an update if everything is alright

**Comment by jgimenez** [comment] 2021-03-15 14:32
Hm I don't get it, do you mean the problem is not within Bugfender?

**Comment by softeip** [comment] 2021-03-15 14:43
Anyway nevermind. Tester has just reproduced this crash again, so my guess is not a reason
I supposed that something was wrong not with bugfender lib but on the app side

**Comment by softeip** [comment] 2021-03-15 16:11
By the way, I could not get NSUserDefaults.standardUserDefaults to return nil. I tried to log it as system calls my handlers of willEnterForegroundNotification and didEnterBackgroundNotification

**Comment by jgimenez** [comment] 2021-03-15 18:18
Yes, I've never been able to reproduce this myself, but people on forums (the links above) said it's possible. Maybe depends on the specifics of the app configuration.

**Comment by jgimenez** [comment] 2021-03-18 17:33
It seems we learned why this is happening: apparently, if the file where user defaults are stored is locked, NSUserDefaults.standardUserDefaults does not return nil, but any queries made to it will.

In the case of our SDK, it is doing a query that should return an array of NSString but it returns an array with 0 as the only element instead. We think this can happen if your application has a "data protection" entitlement and your app is doing some work in the background.

**Comment by softeip** [comment] 2021-03-23 12:01
Were you able to reproduce it? 
In addition to logging of NSUserDefaults.standardUserDefaults, I also tried to print its content (dictionaryRepresentation) and it always returned me correct data.

As for the data protection, device was unlocked and I have not found any data protection mentions in the app's entitlement or info plists

**Comment by jgimenez** [comment] 2021-03-23 12:56
Yes, we were able to reproduce it and we're preparing a release that fixes issues when the application's data is locked. This can happen when the phone is locked but also when the phone is running the app in background mode, which coincides with the case you were mentioning that the user was coming back from giving permissions. The data protection class is usually specified in the .entitlements file in an Xcode project, although I don't know exactly how Xamarin handles this.

**Comment by softeip** [comment] 2021-03-23 12:59
Thank you
Will try new version as soon as it gets released

**Comment by jgimenez** [comment] 2021-03-24 17:20
Released! https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.10.1

I'm closing this for now, please let me know if you keep encountering any issues.

**Closed by jgimenez** 2021-03-24 17:20 UTC

**Comment by jgimenez** [comment] 2021-03-25 10:43
FYI: since you're working on Xamarin.iOS, if you're using our NuGet, it has been updated too: https://www.nuget.org/packages/Bugfender.Sdk/2.0.3
