### ISSUE TITLE
Empty session

### ISSUE THREAD

**Issue by dmitrykurochka** [bugfender/BugfenderSDK-iOS#15] opened 2016-06-14 08:24 UTC
Hi! I have integrated logging and founded that some sessions have no logs at all. But it is impossible - because if user open application - there are several logs should be sended. But bugfender knows about this users and sessions. So users definitely open application. So what possible ways to have zero logs in session?

**Comment by jgimenez** [comment] 2016-06-14 08:40
Hi @dmitrykurochka. It is possible that sessions are temporarily empty while devices are still uploading logs. If the application goes to background quickly it is possible that sessions stay empty until the next execution of the application, since Bugfender does not keep the application awake in the background to send logs.

Could you please tell us the SDK version you are using, iOS versions where this happens, device types, etc.? Does it happen always or only sometimes? What have you tried to reproduce it? Have you integrated the framework with CocoaPods or manually? Yours,

**Comment by dmitrykurochka** [comment] 2016-06-14 08:49
@jgimenez It is latest SDK and iPad Air 2. I have integrated it by CocoaPods. I don't know how to reproduce. It is logs from clients devices. It is around 5% of users

**Comment by jgimenez** [comment] 2016-06-14 15:34
@dmitrykurochka In this case it is very common that the data is simply yet not sent, because the application was closed by the user, but will eventually be sent to the servers.

If you would like us to look specifically into your account, please send an e-mail to support@bugfender.com with your login e-mail and we will look into it.

**Closed** 2016-06-14 17:00 UTC
